  
version: 0.1

workflows:
  on-commit:
    jobs:
    - job-a
    - job-b:
        after:
        - job-c
    - job-c
    - job-d:
        after:
          - job-a
          - job-b
    - job-e:
        after:
        - job-c
    - job-f:
        after:
        - job-c
    - job-g:
        after:
        - job-d
        - job-e
        - job-f
    - job-h
    - job-i:
        after:
        - job-h
    - job-j:
        after:
        - job-h
    - job-k:
        after:
        - job-h

jobs:
  job-a:
    steps:
    - run: sleep 5
  job-b:
    steps:
    - run: sleep 5
  job-c:
    steps:
    - run: sleep 5
  job-d:
    steps:
    - run: sleep 5
  job-e:
    steps:
    - run: sleep 5
  job-f:
    steps:
    - run: sleep 5
  job-g:
    steps:
    - run: sleep 5
  job-h:
    steps:
    - run: sleep 5
  job-i:
    steps:
    - run: sleep 5
  job-j:
    steps:
    - run: sleep 5
  job-k:
    steps:
    - run: sleep 5
